name = "Kaneko"
uuid = "1aada2ef-2a50-48a3-a0b9-a990eafe4182"
authors = ["Isaia Nisoli nisoli@im.ufrj.br and contributors"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DistributedArrays = "aaf54ef3-cdf8-58ed-94cc-d582ad619b94"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = ">= 1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
